export const ADD_DISHES = 'ADD_DISHES';
export const DISHES_LOADING = 'DISHES_LOADING';
export const DISHES_FAILED = 'DISHES_FAILED';

export const FETCH_USER = 'FETCH_USER';
export const LOADING_USER = 'LOADING_USER';
export const FAILED_USER = 'FAILED_USER';

export const ADD_BILLS = 'ADD_BILLS';
export const FAILED_BILLS = 'FAILED_BILLS';
export const LOADING_BILLS = 'LOADING_BILLS';
export const DELETE_BILL = 'DELETE_BILL';
export const ADD_BILL = 'ADD_BILL';

export const FETCH_TABLE = 'FETCH_TABLE';
export const TABLE_LOADING = 'TABLE_LOADING';
export const ERROR_TABLE = 'ERROR_LOADING';

export const FETCH_ALL_USER = 'FETCH_ALL_USER';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const POST_COMMENT = 'POST_COMMENT';
export const FAILED_COMMENTS = 'FAILED_COMMENTS';
export const LOADING_COMMENTS = 'LOADING_COMMENTS';

export const ADD_FAVORITES = 'ADD_FAVORITES';
export const FAILED_FAVORITES = 'FAILED_FAVORITES';
export const LOADING_FAVORITES = 'LOADING_FAVORITES';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const ADD_LOCAL_FAVORITES = 'ADD_LOCAL_FAVORITES';

export const FETCH_RECOMMEND = 'FETCH_RECOMMEND';
